contactApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views


urlpatterns = [
    path('accounts/', include('users.urls')),
    path('contacts/', include('contacts.urls')),
    path('admin/', admin.site.urls),
    re_path(r'static/(.+)', views._static_butler)
]

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.createContact, name='createContact'),
    path('read', views.readContact, name='readContact'),
    path('update/<int:id>/', views.updateContact, name='updateContact'),
    path('delete/<int:id>/', views.deleteContact, name='deleteContact'),
    path('detail/<int:id>/', views.viewDetail, name='detailContact'),
]

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('register/', views.registerUser, name='register'),
    path('logout/', views.logoutUser, name='logout')
]

contacts/models.py
from django.db import models
from django.utils import timezone



class Contact(models.Model):
    firstName = models.CharField(max_length=200)
    lastName = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    website = models.CharField(max_length=200)
    unitNumber = models.IntegerField()
    civicNumber = models.IntegerField()
    street = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    province = models.CharField(max_length=2)
    postalCode = models.CharField(max_length=3)
    createdAt = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.firstName + ' ' + self.lastName
    

users/models.py
from django.db import models
# from django.utils import timezone


# class Users(models.Model):
#     username = models.CharField(max_length=200)
#     password = models.CharField(max_length=200)
#     createdAt = models.DateTimeField(timezone.now())

#     def __str__(self):
#         return self.username

contactApp/views.py
from django.contrib.staticfiles.views import serve as serve_static

def _static_butler(request, path, **kwargs):
    return serve_static(request, path, insecure=True, **kwargs)

contacts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.messages import error, success
from django.db.models import Q
from .utils import addNewContact, doUpdateContact, getAllContacts
from .models import Contact
import logging



@login_required
def index(req):
    return readContact(req)
    


@login_required
def createContact(req):
    if req.method == 'GET':
        return render(req, 'contacts/addContact.html')
    
    return addNewContact(req)



@login_required
def readContact(req):
    readAllContacts = req.GET.get('readall')

    if readAllContacts is None or readAllContacts.lower() == 'yes':
        contacts = getAllContacts()
        if contacts is None:
            logging.error('No contact found.')
            error(req, message='No contact found.')
            return render(req, 'contacts/index.html')
        
        context = {'contacts': contacts}
        if len(contacts) == 0:
            logging.warning('No record found')
            error(req, message='No record found')
        return render(req, 'contacts/index.html', context=context)
            

    firstname = req.GET.get('firstname')
    lastname = req.GET.get('lastname')
    email = req.GET.get('email')


    if len(firstname)==0 and len(lastname)==0 and len(email)==0:
        logging.error('Provide at least one input')
        error(req, message='Provide at least one input')
        return redirect('contacts:index')
    
    
    contacts = Contact.objects.filter(
        Q(firstName__iexact=firstname) |
        Q(lastName__iexact=lastname) |
        Q(email__iexact=email) 
    )
        
    if len(contacts) == 0:
        logging.warning('No record found')
        error(req, message='No record found')
        return render(req, 'contacts/index.html', context={'contacts':contacts})

    context = {'contacts': contacts}
    return render(req, 'contacts/index.html', context=context)
    
    
    

@login_required
def updateContact(req, id):
    if req.method == 'GET':
        if not req.session.get('urlref'):
            req.session['urlref'] = req.META.get('HTTP_REFERER')
        contact = get_object_or_404(Contact, pk=id)
        context = {'contact': contact}
        return render(req, 'contacts/updateContact.html', context=context)

    return doUpdateContact(req, id)    



@login_required
def deleteContact(req, id):
    try:
        contact = Contact.objects.get(pk=id)
    except (KeyError, Contact.DoesNotExist):
        logging.error(KeyError)
        error(req, message='Contact delete failed. Try again')
    else:
        success(req, message='Contact deleted successfully')
        contact.delete()
    return redirect(req.META.get('HTTP_REFERER'))



@login_required
def viewDetail(req, id):
    contact = get_object_or_404(Contact, pk=id)
    context = {'contact': contact}
    return render(req, 'contacts/detail.html', context=context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.messages import error
from .userValidators import ValidateUser
import logging
from .utils import loggedIn, handleDBConnectionError, isUserRegistered



@loggedIn
def loginUser(req):
    if req.method == 'GET':
        return render(req, 'accounts/login.html')
    
    return authenticateUser(req)
    

@handleDBConnectionError
def authenticateUser(req):
    username = req.POST['username']
    password = req.POST['password']

    if not isUserRegistered(username):
        message = f'Username ({username}) not found'
        logging.error(message)
        error(request=req, message=message)
        return redirect('users:login') 

    user = authenticate(request=req, username=username, password=password)

    if user is None:
        message = 'Invalid password'
        logging.error(message)
        error(request=req, message=message)
        return redirect('users:login')
    
    login(req, user)
    return redirect('contacts:index')


@loggedIn
def registerUser(req):
    if req.method  == 'GET':
        return render(req, 'accounts/register.html')
    
    return createUser(req)



@handleDBConnectionError
def createUser(req):
    username = req.POST['username']
    email = req.POST['email']
    password1 = req.POST['password1']

    if isUserRegistered(username):
        message = f'User ({username}) already exists'
        logging.warning(message)
        error(request=req, message=message)
        return redirect('users:register')

    validateUser = ValidateUser(req.POST)
    messages = validateUser.errorMessages
    
    if messages:
        for message in messages:
            logging.error(message)
            error(request=req, message=message)
        return redirect('users:register')

    user = User(username=username, email=email, password=password1)
    user.save()
    user.set_password(user.password)
    user.save()
    return redirect('users:login')
    
    
        
        


def logoutUser(req):
    logout(req)
    return redirect('users:login')



    

templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <title>Login</title>
</head>

<body>
  <div class="container">
    <div class="login form">
      <header>Login</header>
      <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <input type="text" required name="username" placeholder="Enter your username">
        <input type="password" required name="password" placeholder="Enter your password">
        <div>
          {% if messages %}
          {% for message in messages %}
          <p style="text-align: center; color: brown;"><strong>{{ message }}</strong></p>
          {% endfor %}
          {% endif %}
        </div>
        <button type="submit" class="button">Login</button>
      </form>
      <!-- <div class="signup">
        <span class="signup">Don't have an account?
          <a href="{% url 'users:register' %}" for="signup">Signup</a>
        </span>
      </div> -->
    </div>
  </div>
</body>

</html>

templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <title>Register</title>
</head>

<body>
  <div class="container">
    <div class="registration form">
      <header>Signup</header>
      <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <input type="text" required name="username" placeholder="Enter your username">
        <input type="text" required name="email" placeholder="Enter your email">
        <input type="password" required name="password1" placeholder="Create a password">
        <input type="password" required name="password2" placeholder="Confirm your password">
        <div>
          {% if messages %}
          {% for message in messages %}
          <p style="text-align: center; color: brown;"><strong>{{ message }}</strong></p>
          {% endfor %}
          {% endif %}
        </div>
        <button type="submit" class="button">Signup</button>
      </form>
      <div class="signup">
        <span class="signup">Already have an account?
          <a href="{% url 'users:login' %}" for="signup">Login</a>
        </span>
      </div>
    </div>
  </div>
</body>

</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <title>Contact Management</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/contact.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="light-grey content" style="max-width:1600px">

  <div class="main">
    <header id="portfolio">
      <a class="circle right margin hover-opacity bg-light logout-user button" 
        href="#">
        Logout
      </a>
      <div class="container">
        <h3><b>Contact Management System</b></h3>
        <div class="section bottombar padding-16">
          <a class="button bg-light margin-right" href="{% url 'contacts:index' %}">
            Home
          </a>
          <a class="button bg-light margin-left" href="{% url 'contacts:createContact' %}">
            Add Contact
          </a>
        </div>
      </div>
    </header>

    <div class="row-padding" style="margin-left:10px">
        {% block content %}{% endblock %}
    </div>

    <footer class="padding-24 dark-grey">
      <div class="center">
        INSE6250 Winter-2024 Project
      </div>
    </footer>

  </div>

  {% include "contacts/deleteModal.html" %}
  {% include "contacts/logoutModal.html" %}

  
  <script>
    let deleteButtons = document.getElementsByClassName('delete-contact');
    let logoutUser = document.getElementsByClassName('logout-user');
    let deleteModal = document.getElementById('delete-modal');
    let logoutModal = document.getElementById('logout-modal');
    let confirmButton = document.getElementsByClassName('confirm-button');
    let closeModal = document.getElementsByClassName("close-modal");
    let deleteUrl = "/contacts/delete/" 
    let logoutUrl = "/accounts/logout" 
    
    for(let element of closeModal){
        element.onclick = function () {
            deleteModal.style.display = "none";
            logoutModal.style.display = "none";
        }
    }

    displayModal(logoutUser, logoutModal, logoutUrl);
    displayModal(deleteButtons, deleteModal, deleteUrl);
  
    function displayModal(buttons, modal, url) {
      for(let button of buttons){
        button.onclick = function(ele){
          modal.style.display = 'block';
          let paramId = button.getAttribute('contactID')
          let contactName = button.getAttribute('contactName')
          if(contactName){
            document.getElementById('delete-modal-header').innerHTML = `Delete contact of '${contactName}'`
          }
          if(!paramId) paramId = ''
          for (const confirmbtn of confirmButton) {
            confirmButton && confirmbtn.setAttribute('href', `${url}${paramId}/`)
          }
        }
      }
    }
  </script>

</body>
</html>

templates/contacts/addContact.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="addContact container_main">
  <div class="registration form">
    <header>Create Contact</header>
    <form action="{% url 'contacts:createContact' %}" method="post">
      {% csrf_token %}
      <div class="form-flex">
        <input type="text" required name="firstname" placeholder="First Name">
        <input type="text" required name="lastname" placeholder="Last Name">
        <input type="text" required name="company" placeholder="Company">
        <input type="text" required name="phone" id="phone" placeholder="Phone Number">
        <input type="text" required name="email" placeholder="Email Address">
        <input type="text" required name="website" id="website" placeholder="Website Address (http(s)://x.x)">
        <input type="number" required name="unitNumber" placeholder="Unit Number">
        <input type="number" required name="civicNumber" placeholder="Civic Number">
        <input type="text" required name="street" placeholder="Street Code">
        <input type="text" required name="city" placeholder="City">
        <input type="text" required name="province" class="upper" maxlength="2" placeholder="Province (QC)">
        <input type="text" required name="postalCode" class="upper" maxlength="3"
          placeholder="Postal Code (A1A or 1A1)">
      </div>

      {% include "contacts/message.html" %}

      <button type="submit" class="button">Add Contact</button>
    </form>
  </div>
</div>

<script src="{% static 'js/imask.js' %}"></script>
<script>
  const phone = document.getElementById('phone');
  const maskOptions = {
    mask: '+1 (000) 000-0000'
  };
  phone && IMask(phone, maskOptions);
</script>

{% endblock %}

templates/contacts/deleteModal.html
<div id="delete-modal" class="cmodal">
    <div class="modal-content">
        <span class="close close-modal">&times;</span>
        <h3 id="delete-modal-header">Delete Contact?</h3>
        <a class="button bg-cyan close-modal">Cancel</a>
        <a class="button bg-brown confirm-button" id="confirm-button" href="#">Delete</a>
    </div>
</div>

templates/contacts/detail.html
{% extends "base.html" %}

{% block content %}
    {% if contact %}
        <table class="table">
            <tbody>
                <tr><th colspan="100" style="text-align: center;">
                    <h3>Contact Detail</h3>
                </th></tr>
                <tr><td>First Name</td><td>{{ contact.firstName }}</td></tr>
                <tr><td>Last Name</td><td>{{ contact.lastName }}</td></tr>
                <tr><td>Company</td><td>{{ contact.company }}</td></tr>
                <tr><td>Phone</td><td>{{ contact.phone }}</td></tr>
                <tr><td>Email</td><td>{{ contact.email }}</td></tr>
                <tr><td>Website</td><td>{{ contact.website }}</td></tr>
                <tr><td>Unit Number</td><td>{{ contact.unitNumber }}</td></tr>
                <tr><td>Civic Number</td><td>{{ contact.civicNumber }}</td></tr>
                <tr><td>Street</td><td>{{ contact.street }}</td></tr>
                <tr><td>City</td><td>{{ contact.city }}</td></tr>
                <tr><td>Province</td><td>{{ contact.province }}</td></tr>
                <tr><td>Postal Code</td><td>{{ contact.postalCode }}</td></tr>
            </tbody>
        </table>
    {% else %}
        <p style="text-align: center;">No contacts found </p>
    {% endif %}
{% endblock %}

templates/contacts/index.html
{% extends "base.html" %}


{% block content %}

<div class="container_main_">
  
  {% include "contacts/readContact.html" with contacts=contacts %}
</div>

{% endblock %}

templates/contacts/logoutModal.html
<div id="logout-modal" class="cmodal">
    <div class="modal-content">
        <span class="close close-modal">&times;</span>
        <h3>You are about to logout?</h3>
        <a class="button bg-cyan close-modal">Cancel</a>
        <a class="button bg-brown confirm-button" id="confirm-button" href="#">Logout</a>
    </div>
</div>

templates/contacts/message.html
<div style="width_: 100%; text-align: center;">
    {% if messages %}
        {% for message in messages %}
        <p class="{{ message.tags }}" style="text-align: center;">
            <strong>{{ message }}</strong>
        </p>
        {% endfor %}
    {% endif %}
</div>

templates/contacts/modal.html
<div id="contact-modal" class="cmodal">
    <div class="modal-content">
        <span class="close close-modal">&times;</span>
        
        {% block content %}{% endblock %}
        
    </div>
</div>



<script>
    var modal = document.getElementById("contact-modal");
    var closeModal = document.getElementsByClassName("close-modal");
    
    for(let element of closeModal){
        element.onclick = function () {
            modal.style.display = "none";
        }
    }

</script>

templates/contacts/readContact.html
{#% extends "base.html" %#}



{% block content %}
<div class="addContact_ container_main rc-sidenav">

  <div class="form">
    <header>Read Contact</header>
    <form action="{% url 'contacts:index' %}" method="get">
      {#% csrf_token %#}
      <div class="form-flex_" id="form-inputs">
        <input type="text" name="firstname" placeholder="First Name">
        <input type="text" name="lastname" placeholder="Last Name">
        <input type="text" name="email" placeholder="Email Address">
      </div>
      <input type="text" value="no" name="readall" hidden id="readall_hidden">
      <input style="margin: 0 !important; width: 50px;height: 20px; text-align: left;" type="checkbox" 
        id="checkbox" value="no"><label for="checkbox">Read all</label>  
      <button type="submit" class="button">Search Contact</button>
    </form>
  </div>
</div>

<div class="rc-main">
  {% include "contacts/message.html" %}
  {% if contacts %}
    {% include "contacts/viewContact.html" with contacts=contacts %}
  {% else %}
    <p style="text-align: center;">Read contact to view results. Or create new contacts</p>
  {% endif %}
</div>



<script>
  let readall = document.getElementById('checkbox');
  readall && (readall.onchange = function (e) {
    let checked = e.target.checked
    let formElements = document.getElementById('form-inputs')
    formElements.style.display = '';
    document.getElementById('readall_hidden').value = 'no'
    if (checked) {
      resetValue(formElements.children)
      formElements.style.display = 'none';
      document.getElementById('readall_hidden').value = 'yes'
    }
    console.log(e.target.checked)
  })

  function resetValue(formElements) {
    for (element of formElements) {
      element.value = ''
    }
  }
</script>
{% endblock %}

templates/contacts/updateContact.html
{% extends "base.html" %}



{% block content %}
{% if contact %}
<div class="addContact container_main">
  <div class="registration form">
    <header>Update Contact</header>
    <form action="{% url 'contacts:updateContact' contact.id %}" method="post">
      {% csrf_token %}
      <div class="form-flex">
        <input type="text" required value="{{contact.firstName}}" name="firstname" placeholder="First Name">
        <input type="text" required value="{{contact.lastName}}" name="lastname" placeholder="Last Name">
        <input type="text" required value="{{contact.company}}" name="company" placeholder="Company">
        <input type="text" required value="{{contact.phone}}" name="phone" placeholder="Phone Number">
        <input type="text" required value="{{contact.email}}" name="email" placeholder="Email Address">
        <input type="text" required value="{{contact.website}}" name="website" placeholder="Website Address (http(s)://x.x)">
        <input type="number" required value="{{contact.unitNumber}}" name="unitNumber" placeholder="Unit Number">
        <input type="number" required value="{{contact.civicNumber}}" name="civicNumber" placeholder="Civic Number">
        <input type="text" required value="{{contact.street}}" name="street" placeholder="Street Code">
        <input type="text" required value="{{contact.city}}" name="city" placeholder="City">
        <input type="text" required value="{{contact.province}}" name="province" class="upper" maxlength="2" placeholder="Province (QC)">
        <input type="text" required value="{{contact.postalCode}}" name="postalCode" class="upper" maxlength="3" placeholder="Postal Code (A1A or 1A1)">
      </div>
      
      {% include "contacts/message.html" %}
      
      <button type="submit" class="button">Update Contact</button>
    </form>
  </div>
</div>
{% else %}
    <p style="text-align: center;">No contacts found </p>
{% endif %}
{% endblock %}

templates/contacts/viewContact.html
<table class="table">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th class="center" colspan="3">Manage Contact</th>
      </tr>
    </thead>
    <tbody>
      {% for contact in contacts %}
      <tr>
        <td>{{ contact.firstName }}</td>
        <td>{{ contact.lastName }}</td>
        <td>{{ contact.email }}</td>

        <td class="center"><a class="button bg-cyan" 
            id="detailContact{{contact.id}}"
            href="{% url 'contacts:detailContact' contact.id %}">
            detail
          </a></td>

        <td class="center"><a class="button bg-cyan" 
            id="updateContact{{contact.id}}"
            href="{% url 'contacts:updateContact' contact.id %}">
            update
          </a></td>

        <td class="center delete-contact" 
          contactID="{{contact.id}}"
          contactName="{{contact.firstName}} {{contact.lastName}}"
        >
            <a class="button bg-brown" 
              id="deleteContact{{contact.id}}"
              href="#"
            >
            delete
          </a></td>

      </tr>
      {% endfor %}
    </tbody>
</table>